### ISSUE TITLE
Queue delete not working

### ISSUE THREAD

**Issue by tuxx** [cowbell/mopster#10]
Trying to delete a song by highlighting it and then pressing the delete key does not work.
OS: Mac OSX Yosemite (10.10.2)
Browser: Chrome Version 45.0.2454.85 (64-bit)

**Comment by morgoth** [comment]
I'm not using Mac, so I cannot test it now. I'll try with a friend when he comes back from holidays.

**Comment by tuxx** [comment]
I tried compiling the project with npm, bower and ember but got all kinds of errors. If i can get the dev environment running i'll get some better debug information.

**Comment by jirimajer** [comment]
Same here on os x el capitan

**Comment by morgoth** [comment]
You didn't say that there is no "delete" key on mac ;-)
It should be fixed now. Let me know if it works as I'm not using mac and cannot verify it myself.

**Comment by jirimajer** [comment]
works like a charm now thank you :)
