### ISSUE TITLE
Hung on "Loading..."

### ISSUE THREAD

**Issue by damian-w** [cowbell/mopster#13]
Mopster seems to hang if you use "http://" in the hostname.

![screen shot 2016-01-12 at 10 44 17 pm](https://cloud.githubusercontent.com/assets/1239655/12266535/a6678534-b97e-11e5-9cd9-5425a5d2ec37.png)

**Comment by morgoth** [comment]
Yes, hopefully current form is more clear. You can always enter this screen again from link at bottom of the page. I still need to do some better error handling in case of failed connection.
