### ISSUE TITLE
Delete functionality not working

### ISSUE THREAD

**Issue by damian-w** [cowbell/mopster#16]
Unable to remove songs from the queue using the method described at the bottom of the queue.

Tried using the Delete key on a Mac, using latest Mopidy & Mopster clients.

**Comment by morgoth** [comment]
I'm not using mac so I cannot test it myself, but I fixed this bug some time ago by https://github.com/cowbell/mopster/commit/dc6a352ac490f08d5b9a20fddffb4bbe4e8227a7
