### ISSUE TITLE
Browse -> Local Media -> Artist shows empty list

### ISSUE THREAD

**Issue by jesper216** [cowbell/mopster#17]
Hi,

I just installed Mopster on my client running Mopidy and have the following issue:
When I browse for local music, artist and album lists remain empty. Browsing for tracks works fine. Data is scanned correctly to the sqlite database and testing on other clients gives positive results (i.e. artists show up as they should).

When searching for music, for example searching an artist, shows all songs by this artist however the artist and album lists remain empty

Mopidy version: 2.1.0
Mopidy SQLite extension version: 1.0.0

**Comment by morgoth** [comment]
Closing as stale
