### ISSUE TITLE
Online Version is down

### ISSUE THREAD

**Issue by OberstVonGatow** [cowbell/mopster#24]
If i try to open the Online Version http://mopster.cowbell-labs.com/
I get a 404 Error:
There isn't a GitHub Pages site here.

**Comment by m9aertner** [comment]
Check http://mopster.urizen.pl/

By the way, thanks Cowbell Labs for this cool tool! 💯

**Comment by morgoth** [comment]
I didn't know that anyone is using it except me ;-)
